version: '3.8'

services:
  authenticate:
    build:
      context: .
      dockerfile: ./authenticate/Dockerfile
    container_name: authenticate
    working_dir: /var/www
    volumes:
      - ./authenticate:/var/www
    networks:
      - laravel_network
    expose:
      - "9000"

  nginx_authenticate:
    image: nginx:latest
    container_name: authenticate_nginx
    ports:
      - "8000:8000"
    volumes:
      - ./authenticate/default.conf:/etc/nginx/conf.d/default.conf
      - ./authenticate:/var/www
    depends_on:
      - authenticate
    networks:
      - laravel_network

  logger:
    build:
      context: .
      dockerfile: ./logger/Dockerfile
    container_name: logger
    working_dir: /var/www
    volumes:
      - ./logger:/var/www
    networks:
      - laravel_network
    expose:
      - "9000"

  nginx_logger:
    image: nginx:latest
    container_name: nginx_logger
    ports:
      - "8001:8000"
    volumes:
      - ./logger/default.conf:/etc/nginx/conf.d/default.conf
      - ./logger:/var/www
    depends_on:
      - logger
    networks:
      - laravel_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "15671:15671"
      - "5672:5672"
    networks:
      - laravel_network


networks:
  laravel_network:
    driver: bridge

volumes:
  laravel_app_data:
  mysql_data:
